import { NextResponse } from 'next/server';
import { createAdminClient } from '@/utils/supabase/admin';

export async function POST(request: Request) {
    try {
        const body = await request.json();
        const rows = body.rows; // Array of parsed records

        if (!Array.isArray(rows) || rows.length === 0) {
            return NextResponse.json({ error: 'No data provided' }, { status: 400 });
        }

        const supabase = createAdminClient();

        // Upsert expects primary key or unique fields. 
        // Assuming image_url is unique OR we can simply bulk insert/onConflict logic.
        // For Supabase, upsert requires matching unique constraints. We use `image_url` if it's unique, otherwise `id`.
        // Since OCR usually imports fresh items or overrides matched images, we use `onConflict: 'image_url'` 
        // Wait, let's keep it safe. If image_url isn't explicitly marked UNIQUE in DB, upsert will fail.
        // Assuming 'id' is generated by default if missing, or we upsert purely by `name_en`/`image_url`.
        // We will just do a standard insert, and if they have IDs, upsert them.

        const { data, error } = await supabase
            .from('products')
            .upsert(rows, { onConflict: 'image_url', ignoreDuplicates: false })
            .select('id');

        if (error) {
            console.error('Bulk Import Error:', error);
            return NextResponse.json({ error: error.message }, { status: 500 });
        }

        return NextResponse.json({
            success: true,
            count: data?.length || 0
        });

    } catch (error: Error | unknown) {
        if (error instanceof Error) {
            console.error('Import Route Error:', error);
            return NextResponse.json({ error: error.message }, { status: 500 });
        } else {
            console.error('Import Route Error:', error);
            return NextResponse.json({ error: 'Unknown server error' }, { status: 500 });
        }
    }
}
